### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by damonjones** [mattbspector/LineHop#1]
[Warning] Invalid CSS property declaration at: , (main.css, line 2880)

``` css
#intro {
    …
    background-repeat: no-repeat;, no-repeat;
}
```

[Error] Failed to load resource: The requested URL was not found on this server. (intro.jpg, line 0)

``` css
#intro {
    background: url("images/standinginline.jpg"), url("../../images/intro.jpg");
    …
}
```

[Error] Failed to load resource: The requested URL was not found on this server. (one.jpg, line 0)

``` css
#one {
    background: url("images/AboutUs.jpg"), url("../../images/one.jpg");
    …
```

[Error] Failed to load resource: The requested URL was not found on this server. (two.jpg, line 0)

``` css
#two {
    background: url("images/Press.jpg"), url("../../images/two.jpg");
    …
}
```
